### ISSUE TITLE
Property "stopped" remains false after the sound ended.

### ISSUE THREAD

**Issue by stnk20** [roccomuso/node-aplay#7]
Property `stopped` remains `false` after the sound ended.
It is expected `true` when checking whether the sound ended.

Inserting
`self.stopped = true`
in
`this.process.on('exit', ...)` 
solves this problem.

https://github.com/roccomuso/node-aplay/blob/65cdb090538d44184d189a23ab09a440eb75280a/node-aplay.js#L35

**Comment by roccomuso** [comment]
yes. Good catch. I'll update it right now. 5b551b3
